user:
  image: dev.registry:5000/user:latest

haproxy:
  image: haproxy:1.6.2
  links:
    - user
  ports:
    - "80:80"
    - "70:70"
  volumes:
    - ./configs/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg